name: Test DD-VMS ROM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install torch skorch numpy pandas
        pip install -e .

    - name: Install gdown
      run: |
        pip install gdown
        gdown https://drive.google.com/uc?id=1-5ryuIACyWtOzSl3y0y0SYKBqIGofrO3

    - name: Install unzip
      run: |
        sudo apt-get install -y unzip
        unzip Re200.zip

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)/" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest tests/test_ddvmsrom.py
